server:
  port: 8085
  servlet:
    context-path: /consul-service

spring:
  application:
    name: consul-service
  profiles:
    active: dev
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8888/eureka/
