server:
  port: 8089
  servlet:
    context-path: /gateway-service

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # This route rule used to forward request to activity server
        - id: zipkin-route
          uri: lb://ZIPKIN-SERVICE
          predicates:
            - Path=/zipkin/**
          filters:
            - StripPrefix=1
  profiles:
    active: dev
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8888/eureka/