server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paas?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.htsc.user.pojo
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8888/eureka/

logging:
  level:
    com.htsc: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS