server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8888/eureka/
spring:
  application:
    name: order-service
  profiles:
    active: dev
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092