server:
  port: 9900

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #     声明是否将自己的信息注册到 Eureka 服务器上
    registerWithEureka: false
    #     是否到 Eureka 服务器中抓取注册信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${server.port}/eureka/


spring:
  application:
    name: eurka-service
  security:
    user:
      name: admin
      password: admin
  profiles:
    active: dev